services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - i_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - i_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
    ports:
      - 3306:3306
    networks:
      - i_network
    volumes:
      - mariadb_volume:/var/mysql

networks:
  i_network:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_volume:
