services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - i_network
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - i_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html

networks:
  i_network:
    driver: bridge

volumes:
  wordpress_data:
