services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      .env
    networks:
      - i_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - i_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      .env
    ports:
      - "3306"
    networks:
      - i_network
    volumes:
      - mariadb_volume:/var/lib/mysql

networks:
  i_network:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_volume:
